spring:
  profiles:
    active:
    - dev
#分隔符
--- 
spring:
  profiles: dev     #开发环境
  application: 
    name: microservicecloud-config-youngnzhi-dev
---
spring:
  profiles: test    #测试环境
  application: 
    name: microservicecloud-config-youngnzhi-test
#请保存为UTF-8格式
